### ISSUE TITLE
Getters for Setters so state can be restored

### ISSUE THREAD

**Issue by JGeerWM** [wallabyway/forge-pdf-report#1]
There are a couple calls to setPostProcessParameter and one to setBackgroundColor.  If I wanted to repurpose a viewer in order to generate pdf reports from a large model, it would be ideal to capture state with some get...() equivalent of the above functions.  Then, when done processing the pdf report, I could restore state.  With out a way to restore state, I would need to throw away the viewer and this is expensive on large models

**Comment by wallabyway** [comment]
True, there is no 'getter' to find the state of postProcessing.  However, all models default to the off state on startup.
So, when you restore the viewer state (using restoreState), you would also turn off postprocessing, with...
 viewer.impl.setPostProcessParameter("style", "");
viewer.impl.setPostProcessParameter("brightness",0.0);
